### ISSUE TITLE
[Bug] Unable to sign into Android app

### ISSUE THREAD

**Issue by Bestivus** [orbforge/orb-issues#59]
**Describe the bug**
Orb on Android, when attempting to sign into my account by tapping "Sign in", the button quickly changes to something unreadable then goes back to "Sign in" without actually logging in or presenting a login screen on the website.

**To Reproduce**
1. Open Orb on an Android device
2. Tap "Sign in"
3. App does not sign in

**Expected behavior**
Tapping the button to sign in should sign into the account 

**Environment (please complete the following information):**
- OS: Android
- OS Version: 16, latest security patch
- Orb App Version: ord-mobile 1.2.0.32f1973

![Screenshot_20250817-203352.png](https://github.com/user-attachments/assets/cfb2669b-3dce-473c-9316-9d902dc95166)

**Comment by meaghanbauman607** [comment]
Sign in issues have been resolved for Android (and other platforms) since launch

**Comment by Farrit1184** [comment]
> Sign in issues have been resolved for Android (and other platforms) since launch

They are still happening though? This exact issue is happening for me too, both on the stable release and on the beta release (when downloaded from Google Play store.) 

I have tried clearing cache, clearing data, reinstalling... When you click the "Sign in" button, a little spin icon will show for a split second, then nothing happens.


I'm on a Pixel 8 Pro, running Orb version 1.3.4, Android version 16, security update November 5, 2025

**Comment by charlesnadeau** [comment]
I still can't sign-in. Motorola Edge 50 Neo, Orb 1.4.0, Android 15, security update October 23rd 2025. Without the ability to sign-in, it is useless.
Thanks!

Charles
